[package]
name = "strategy-host-test"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.43", default-features = false, features = ["serde", "alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
